on:
  push:
  schedule:
    - cron: '50 * * * *'

jobs:
  run:
    name: Push forecast to b2
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        run: |
          mkdir ./weather_forecasts
          curl -s -o ./weather_forecasts/city_scrape.sh "https://raw.githubusercontent.com/semiformal-net/weather_forecasts/master/city_scrape.sh"
          chmod 777 ./weather_forecasts/city_scrape.sh
          echo "ok got cityscrape"

      - shell: bash
        run: |
          ./weather_forecasts/city_scrape.sh
          echo "run scrape"

      - uses: sylwit/install-b2-cli-action@v1.0.1
        env:
          B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}

      - name: tarcheck
        run: |
          echo "path: ${{env.output_tar_path}}"
          echo "name: ${{env.output_tar}}"
      - name: b2sync
        run: b2 upload-file --noProgress --threads 1 weather-forecasts "${{env.output_tar_path}}" "${{env.output_tar}}"
