on:
  push:
  schedule:
    - cron: '32 * * * *'

jobs:
  run:
    name: Push forecast to b2
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        run: |
          mkdir ./weather_forecasts
          curl -s -o ./weather_forecasts/city_scrape.sh "https://raw.githubusercontent.com/semiformal-net/weather_forecasts/master/city_scrape.sh"
          chmod 777 ./weather_forecasts/city_scrape.sh
          echo "ok got cityscrape"

      - shell: bash
        run: |
          ./weather_forecasts/city_scrape.sh
          echo "run scrape"

      - uses: sylwit/install-b2-cli-action@v1.0.0
        env:
          B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}

      - name: b2sync
        run: b2 sync --noProgress ./weather_forecasts/forecast_xml/ b2://weather-forecasts
