on:
  schedule:
    - cron: '15 * * * *'

jobs:
  run:
    name: Get forecast
    runs-on: ubuntu-latest

    steps:
      - run: |
          mkdir ./weather_forecasts
          curl -s -o ./weather_forecasts/city_scrape.sh "https://raw.githubusercontent.com/semiformal-net/weather_forecasts/master/city_scrape.sh"
          chmod 777 ./weather_forecasts/city_scrape.sh
        shell: bash

      - run: ./weather_forecasts/city_scrape.sh
        shell: bash

      # ...and then use the action as you would normally do, but providing the path to the repo
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Add the forecast'
          add: '*.xml --force'
          cwd: './weather_forecasts/'
