on:
  schedule:
    - cron: '26 * * * *'

jobs:
  run:
    name: Get forecast
    runs-on: ubuntu-latest

    steps:
      # If you need to, you can check out your repo to a different location
      - uses: actions/checkout@v3
        with:
          path: './weather_forecasts/'

      - run: |
          curl -s https://weather.gc.ca/rss/city/on-143_e.xml -o ./weather_forecasts/forecast_xml/on-143_e$(date +\%s).xml 

      # ...and then use the action as you would normally do, but providing the path to the repo
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Add the forecast'
          add: '*.xml --force'
          cwd: './weather_forecasts/'
