on:
  schedule:
    - cron: '08 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Get forecast
        run: |
          curl -s https://weather.gc.ca/rss/city/on-143_e.xml -o forecast_xml/on-143_e$(date +\%s).xml 
